version: '3.9'

services:
  go_db:
    container_name: go_db
    image: postgres:14
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '54321:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}