port: ":8080"
env: staging
app_code: backend_testiing
db: 
  host: localhost
  username: postgres
  password: postgres
  name: backend_test_sanberhub_test
  port: 5432
jwt_encryption_key: 9c1d50f1bda04eaf919b15428e6b8676